openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "small-things-to-do api specs"
  description: "API specifications for pet project small-things-to-do"
servers:
  - url: "https://localhost:3001/api"
    description: "Local host server for api"
components:
  securitySchemes:
    # See https://demo.identityserver.io/ for configuration details.
    identity_server_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://demo.identityserver.io/connect/authorize"
          scopes:
            api: "api"
security:
  - identity_server_auth:
    - api
    
paths:
  /test:
    get:
      summary: "Runs a test request against the Identity Server demo API"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"