openapi: '3.0.0'
info:
  version: '0.0.1'
  title: 'small-things-to-do api specs'
  description: 'API specifications for pet project small-things-to-do'
servers:
  - url: 'https://localhost:3001/api'
    description: 'Local host server for api'

paths:
  /todos/{todoId}:
    get:
      summary: 'Returns a single todo item'
      parameters:
        - $ref: '#/components/parameters/todoId'
      responses:
        200:
          description: 'Todo item'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
              examples:
                GetTodoResponse:
                  $ref: '#/components/examples/GetTodoResponse'
        400:
          description: 'System error message'
        403:
          description: 'Error message for forbidden action'
        404:
          description: 'Error message if todo item does not exist'
    patch:
      summary: 'Updates a specific todo item'
      parameters:
        - $ref: '#/components/parameters/todoId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo-base'
            examples:
              CreateTodoBody:
                $ref: '#/components/examples/CreateTodoBody'
      responses:
        200:
          description: 'Updated todo item'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
              examples:
                GetTodoResponse:
                  $ref: '#/components/examples/GetTodoResponse'
        400:
          description: 'System error message'
        403:
          description: 'Error message for forbidden action'
        404:
          description: 'Error message if todo item does not exist'
    delete:
      summary: 'Deletes a specific todo item'
      parameters:
        - $ref: '#/components/parameters/todoId'
      responses:
        204:
          description: 'Simple message for successfull deletion'
        400:
          description: 'System error message'
        403:
          description: 'Error message for forbidden action'
        404:
          description: 'Error message if todo item does not exist'

  /todos:
    get:
      summary: 'Lists the users todos. The user id is recovered from the jwt token'
      responses:
        200:
          description: 'List of todos'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
              examples:
                ListTodosResponse:
                  $ref: '#/components/examples/ListTodosResponse'
        400:
          description: 'System error message'
        403:
          description: 'Error message for forbidden action'
    post:
      summary: 'Create new todo item'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo-base'
            examples:
              CreateTodoBody:
                $ref: '#/components/examples/CreateTodoBody'
      responses:
        201:
          description: 'Returns the created todo item'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
              examples:
                GetTodoResponse:
                  $ref: '#/components/examples/GetTodoResponse'
        400:
          description: 'System error message'
        403:
          description: 'Error message for forbidden action'

components:
  parameters:
    todoId:
      name: todoId
      in: path
      required: true
      schema:
        type: string

  schemas:
    Todo-base:
      type: object
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 30
        description:
          type: string
          maxLength: 300
        dueDate:
            type: string
      required:
        - title
        - dueDate
    Todo:
      allOf:
        - $ref: '#/components/schemas/Todo-base'
        - type: object
          properties:
            id:
              type: string
            creationDate:
              type: string
            owner:
              type: string
              format: email
          required:
            - id
            - title
            - creationDate
            - dueDate
            - owner
          
  examples:
    GetTodoResponse:
      value: &GetTodoResponse
        id: 636a5fed17e22119f36801db
        title: Wash dishes
        description: Remember to wash the dishes before the guests arrive
        owner: johntest@email.com
        dueDate: 2022-12-05T14:48:00.000Z
        creatioinDate: 2022-12-01T14:48:00.000Z
    ListTodosResponse:
      value:
        - *GetTodoResponse
    CreateTodoBody:
      value:
        title: Wash dishes
        description: Remember to wash the dishes before the guests arrive
        dueDate: 2022-12-05T14:48:00.000Z
        